export enum WordKeyEnum {
  WORD = 'word',
  READING = 'reading',
}

export enum DefinitionKeyEnum {
  MEANING = 'meaning',
  DESCRIPTION = 'description',
}

/**
 * Documentation reference : {@link http://www.edrdg.org/jmwsgi/edhelp.py?svc=jmdict&sid=#kw_pos}
 */
export enum DefinitionTypeEnum {
  ADJ_F = 'adj-f',
  ADJ_I = 'adj-i',
  ADJ_IX = 'adj-ix',
  ADJ_KARI = 'adj-kari',
  ADJ_KU = 'adj-ku',
  ADJ_NA = 'adj-na',
  ADJ_NARI = 'adj-nari',
  ADJ_NO = 'adj-no',
  ADJ_PN = 'adj-pn',
  ADJ_SHIKU = 'adj-shiku',
  ADJ_T = 'adj-t',
  ADV = 'adv',
  ADV_TO = 'adv-to',
  AUX = 'aux',
  AUX_ADJ = 'aux-adj',
  AUX_V = 'aux-v',
  CONJ = 'conj',
  COP = 'cop',
  CTR = 'ctr',
  EXP = 'exp',
  INT = 'int',
  N = 'n',
  N_ADV = 'n-adv',
  N_PR = 'n-pr',
  N_PREF = 'n-pref',
  N_P = 'n-p',
  N_SUF = 'n-suf',
  N_T = 'n-t',
  NUM = 'num',
  PN = 'pn',
  PREF = 'pref',
  PRT = 'prt',
  SUF = 'suf',
  UNC = 'unc',
  V_UNSPEC = 'v-unspec',
  V1 = 'v1',
  V1_S = 'v1-s',
  V2A_S = 'v2a-s',
  V2B_K = 'v2b-k',
  V2B_S = 'v2b-s',
  V2D_K = 'v2d-k',
  V2D_S = 'v2d-s',
  V2G_K = 'v2g-k',
  V2G_S = 'v2g-s',
  V2H_K = 'v2h-k',
  V2H_S = 'v2h-s',
  V2K_K = 'v2k-k',
  V2K_S = 'v2k-s',
  V2M_K = 'v2m-k',
  V2M_S = 'v2m-s',
  V2N_S = 'v2n-s',
  V2R_K = 'v2r-k',
  V2R_S = 'v2r-s',
  V2S_S = 'v2s-s',
  V2T_K = 'v2t-k',
  V2T_S = 'v2t-s',
  V2W_S = 'v2w-s',
  V2Y_K = 'v2y-k',
  V2Y_S = 'v2y-s',
  V2Z_K = 'v2z-k',
  V4B = 'v4b',
  V4G = 'v4g',
  V4H = 'v4h',
  V4K = 'v4k',
  V4M = 'v4m',
  V4N = 'v4n',
  V4R = 'v4r',
  V4S = 'v4s',
  V4T = 'v4t',
  V5ARU = 'v5aru',
  V5B = 'v5b',
  V5G = 'v5g',
  V5K = 'v5k',
  V5K_S = 'v5k-s',
  V5M = 'v5m',
  V5N = 'v5n',
  V5R = 'v5r',
  V5R_I = 'v5r-i',
  V5S = 'v5s',
  V5T = 'v5t',
  V5U = 'v5u',
  V5U_S = 'v5u-s',
  V5URU = 'v5uru',
  VI = 'vi',
  VK = 'vk',
  VN = 'vn',
  VR = 'vr',
  VS = 'vs',
  VS_C = 'vs-c',
  VS_I = 'vs-i',
  VS_S = 'vs-s',
  VT = 'vt',
  VZ = 'vz',
  TEST = 'test',
}
