import { colors } from './Colors';
const KANJI_PROGRESSION_MAX = 20;
const KANJI_PROGRESSION_INC = 2;
const KANJI_PROGRESSION_INC_LOW = 1;

export { colors, KANJI_PROGRESSION_MAX, KANJI_PROGRESSION_INC, KANJI_PROGRESSION_INC_LOW };
