export const screenNames = {
  ONBOARDING: 'Onboarding',
  HOME: 'Home',
  CATEGORIES: 'Categories',
  DIFFICULTIES: 'Difficulties',
  KANJIS: 'Kanjis',
  KANJI: 'Kanji',
  OCR: 'Ocr',
  TRAINING: 'Training',
  EVALUATION: 'Evaluation',
  WORD_EVALUATION: 'WordEvaluation',
  PREMIUM: 'Premium',
  SEARCH: 'Search',
  SETTINGS: 'Settings',
  PROFILE: 'Profile',
  WORD: 'Word',
};
