export const ONBOARDING_FINISHED_KEY = 'ONBOARDING_FINISHED';
export const LANGUAGE_OVERRIDE_KEY = 'LANGUAGE_OVERRIDE';
export const THEME_OVERRIDE_KEY = 'THEME_OVERRIDE';
export const LAST_KNOWN_REGISTRATION_KEY = 'LAST_KNOWN_REGISTRATION';
export const FLASHCARD_PROGRESS_KEY = 'FLASHCARD_PROGRESS';
export const WORD_FLASHCARD_PROGRESS_KEY = 'WORD_FLASHCARD_PROGRESS';
