# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [api]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "back"
          docker_build_args: |
            SAVED_MODEL_URL
            AWS_ACCESS_ID
            AWS_ACCESS_SECRET
            AWS_BUCKET_NAME
            MONGO_URI
            MONGO_DB_NAME
            MONGO_COLLECTION
            PORT

        env:
          SAVED_MODEL_URL: ${{ secrets.SAVED_MODEL_URL }}
          AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          MONGO_URI: ${{ secrets.MONK_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
          PORT: 80
